### ISSUE TITLE
Attack frequency

### ISSUE THREAD

**Issue by battlecatsinfo** [AAGaming138/Cat-Page#1]
In `Scripts/StatsCommon.py`, function `get_atkanim`

The method that you calculate frame length is not correct, for example, Cat #13 (女王貓)(First Form) and Cat 451(貓若丸/うしわか丸)  and Cat 673(ネコチーター) will have negative backswing.

Here are the method used in BCU(I translated into python)

https://github.com/battlecatsultimate/BCU_java_util_common

```python
class Part:
    def __init__(self, f):
        ss = next(f).strip().split(',')
        self.ints = []
        for i in range(5):
            self.ints.append(int(ss[i]))
        self.n = int(next(f).strip())
        self.moves = []
        for i in range(self.n):
            x = next(f).strip().split(',')
            y = []
            for i in range(4):
                y.append(int(x[i]))
            self.moves.append(y)
        self.validate()
    def getMax(self):
        return self.fir + (self.max - self.fir) * self.ints[2] if self.ints[2] > 1 else self.max
    def validate(self):
        doff = 0
        if self.n and (self.moves[0][0] < 0 or self.ints[2] > 1):
            doff -= self.moves[0][0]
        for i in range(self.n):
            self.moves[i][0] += doff
        self.off = doff
        self.fir = self.moves[0][0] if len(self.moves) else 0
        self.max = self.moves[self.n - 1][0] if self.n > 0 else 0

class MaAnim: # MaAnim.java
	def __init__(self, path):
		f = open(path)
		next(f)
		next(f)
		n = int(next(f).strip())
		self.parts = []
		for i in range(n):
			self.parts.append(Part(f))
		self.validate()
	def validate(self):
		self.len = 1
		for part in self.parts:
			x = part.getMax() - part.off
			if x > self.len:
				self.len = x

x = MaAnim('./data/unit/013/f/013_f02.maanim')

print(x.len + 1) # attack length, getAtkLen()=45f

# long_pre = 28f
# tba = 6f
# backswing = getAtkLen() - long_pre = 45 - 28 = 17f
# atkfreq = long_pre + max(tba - 1, backswing) = 28 + 17 = 45f

#   === DefaultData.java ===
# 	@Override
#	public int getPost() {
#		return getAnimLen() - getLongPre();
#	}
#   === AnimU.java ===
#	public int getAtkLen() {
#		partial();
#		return anims[2].len + 1;
#	}
#	protected void partial() {
#		if (!partial) {
#			partial = true;
#			mamodel = loader.getMM();
#			anims = loader.getMA();
#		}
#	}
#   === Form.java ===
#	protected Form(Unit u, int f, String str, String data) {
#		... skip ...
#		anim = new AnimUD(str, nam, "edi" + nam + ".png", "uni" + nam + "00.png");
#		... skip ...
#	}
#   === AnimUD.java
#	public MaAnim[] getMA() {
#		MaAnim[] ma;
#		if (VFile.getFile(spath + "_zombie00.maanim") != null)
#			ma = new MaAnim[7];
#		else if (VFile.getFile(spath + "_entry.maanim") != null)
#			ma = new MaAnim[5];
#		else
#			ma = new MaAnim[4];                                 // here
#		for (int i = 0; i < 4; i++)                             // here
#			ma[i] = MaAnim.newIns(spath + "0" + i + ".maanim"); // here
#		if (ma.length == 5)
#			ma[4] = MaAnim.newIns(spath + "_entry.maanim");
#		if (ma.length == 7)
#			for (int i = 0; i < 3; i++)
#				ma[i + 4] = MaAnim.newIns(spath + "_zombie0" + i + ".maanim");
#		return ma;
#	}
```

**Comment by battlecatsinfo** [comment]
And In `Scripts/Cat.py`, function `getNPCost()`

```python
            return sum(costs), True if len(costs) > 2 else False
```

equivalent to
```python
            return sum(costs), len(costs) > 2
```

**Comment by battlecatsinfo** [comment]
As for enemies, maybe it's BCU's bug?

![1](https://github.com/AAGaming138/Cat-Page/assets/139135933/91a3afc3-f53d-45bf-aae1-0a2367fc9880)

**Comment by AAGaming138** [comment]
> In `Scripts/StatsCommon.py`, function `get_atkanim`
> 
> The method that you calculate frame length is not correct, for example, Cat #13 (女王貓)(First Form) and Cat 451(貓若丸/うしわか丸) and Cat 673(ネコチーター) will have negative backswing.
> 
> Here are the method used in BCU(I translated into python)
> 
> https://github.com/battlecatsultimate/BCU_java_util_common
> 
> ```python
> class Part:
>     def __init__(self, f):
>         ss = next(f).strip().split(',')
>         self.ints = []
>         for i in range(5):
>             self.ints.append(int(ss[i]))
>         self.n = int(next(f).strip())
>         self.moves = []
>         for i in range(self.n):
>             x = next(f).strip().split(',')
>             y = []
>             for i in range(4):
>                 y.append(int(x[i]))
>             self.moves.append(y)
>         self.validate()
>     def getMax(self):
>         return self.fir + (self.max - self.fir) * self.ints[2] if self.ints[2] > 1 else self.max
>     def validate(self):
>         doff = 0
>         if self.n and (self.moves[0][0] < 0 or self.ints[2] > 1):
>             doff -= self.moves[0][0]
>         for i in range(self.n):
>             self.moves[i][0] += doff
>         self.off = doff
>         self.fir = self.moves[0][0] if len(self.moves) else 0
>         self.max = self.moves[self.n - 1][0] if self.n > 0 else 0
> 
> class MaAnim: # MaAnim.java
> 	def __init__(self, path):
> 		f = open(path)
> 		next(f)
> 		next(f)
> 		n = int(next(f).strip())
> 		self.parts = []
> 		for i in range(n):
> 			self.parts.append(Part(f))
> 		self.validate()
> 	def validate(self):
> 		self.len = 1
> 		for part in self.parts:
> 			x = part.getMax() - part.off
> 			if x > self.len:
> 				self.len = x
> 
> x = MaAnim('./data/unit/013/f/013_f02.maanim')
> 
> print(x.len + 1) # attack length, getAtkLen()=45f
> 
> # long_pre = 28f
> # tba = 6f
> # backswing = getAtkLen() - long_pre = 45 - 28 = 17f
> # atkfreq = long_pre + max(tba - 1, backswing) = 28 + 17 = 45f
> 
> #   === DefaultData.java ===
> # 	@Override
> #	public int getPost() {
> #		return getAnimLen() - getLongPre();
> #	}
> #   === AnimU.java ===
> #	public int getAtkLen() {
> #		partial();
> #		return anims[2].len + 1;
> #	}
> #	protected void partial() {
> #		if (!partial) {
> #			partial = true;
> #			mamodel = loader.getMM();
> #			anims = loader.getMA();
> #		}
> #	}
> #   === Form.java ===
> #	protected Form(Unit u, int f, String str, String data) {
> #		... skip ...
> #		anim = new AnimUD(str, nam, "edi" + nam + ".png", "uni" + nam + "00.png");
> #		... skip ...
> #	}
> #   === AnimUD.java
> #	public MaAnim[] getMA() {
> #		MaAnim[] ma;
> #		if (VFile.getFile(spath + "_zombie00.maanim") != null)
> #			ma = new MaAnim[7];
> #		else if (VFile.getFile(spath + "_entry.maanim") != null)
> #			ma = new MaAnim[5];
> #		else
> #			ma = new MaAnim[4];                                 // here
> #		for (int i = 0; i < 4; i++)                             // here
> #			ma[i] = MaAnim.newIns(spath + "0" + i + ".maanim"); // here
> #		if (ma.length == 5)
> #			ma[4] = MaAnim.newIns(spath + "_entry.maanim");
> #		if (ma.length == 7)
> #			for (int i = 0; i < 3; i++)
> #				ma[i + 4] = MaAnim.newIns(spath + "_zombie0" + i + ".maanim");
> #		return ma;
> #	}
> ```

This is already accounted for, see `getTables` method in `Scripts/CatPage.py`, as well as `getStats` method in `Scripts/EnemyPage.py`.
